# Generated by Django 2.2.16 on 2020-10-14 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.BigIntegerField(verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='text',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
    ]
