# Generated by Django 2.2.16 on 2020-10-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
